---
docker_rit_deploy_nginx: false
docker_rit_deploy_portainer: false #nginx required
docker_rit_deploy_grafana: false #nginx required
docker_rit_deploy_ldap_passwd_webui: false #nginx required
docker_rit_deploy_bookstack: false #nginx required

docker_rit:
  ldap_passwd_webui:
    host: 172.17.110.254
    port: 636
    use_ssl: true
    base: ou=People,dc=rit,dc=va
    ad_domain: rit.va
  bookstack:
    url: https://bookstack.rit
  bookstack_db:
    host: bookstack_db
    root_password: jHHQ3cuN5aWxfGzJ
    database: bookstack
    user: bookstack
    password: TJMgaDwhy25bLxb7

# Nginx config parameters
nginx_conf_enable_gzip: true
nginx_static_enable_optimization: true

nginx_conf_user: nginx
nginx_conf_worker_processes: auto
nginx_conf_worker_connections: 1024
nginx_conf_keepalive_timeout: 65
