---
- name: ldap-passwd-webui | Create a directories for ldap-passwd-webui it does not exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: toolset
    group: toolset
    mode: '0755'
  with_items:
    - /h/toolset/ldap-passwd-webui
    - /h/toolset/ldap-passwd-webui/source

- name: ldap-passwd-webui | Git clone project source.
  git:
    repo: git@git.rit:sysadm/ldap-passwd-webui.git
    dest: /h/toolset/ldap-passwd-webui/source
    accept_hostkey: yes
    # update: no # ignore error if files changed
    force: yes # replace files if local modifications exist in repository
  # become_user: toolset
  ignore_errors: "{{ ansible_check_mode }}"

- name: ldap-passwd-webui | Copying files to build an image.
  copy:
    src: "ldap-passwd-webui/{{ item }}"
    dest: /h/toolset/ldap-passwd-webui/
    owner: toolset
    group: toolset
    mode: 0644
  with_items:
    - Dockerfile
    - varb-ca.crt

- name: ldap-passwd-webui | Copy settings.ini.
  template:
    src: ldap-passwd-webui/settings.ini.j2
    dest: /h/toolset/ldap-passwd-webui/settings.ini
    owner: toolset
    group: toolset
    mode: 0644

- name: ldap-passwd-webui | Build an ldap-passwd-webui image.
  docker_image:
    build:
      path: /h/toolset/ldap-passwd-webui/
    name: ldap-passwd-webui
    tag: v1
    source: build
  ignore_errors: "{{ ansible_check_mode }}"

- name: ldap-passwd-webui | Create a ldap-passwd-webui container.
  docker_container:
    name: ldap-passwd-webui
    image: ldap-passwd-webui:v1
    networks:
      - name: "default_network"
    restart_policy: unless-stopped
  ignore_errors: "{{ ansible_check_mode }}"

- name: ldap-passwd-webui | Copy tls certificates.
  copy:
    src: "ldap-passwd-webui/nginx/tls/{{ item.src }}"
    dest: /h/toolset/nginx/tls/
    owner: toolset
    group: toolset
    mode: "{{ item.mode }}"
  with_items:
    - { src: "password.rit.crt", mode: "0644" }
    - { src: "password.rit.key", mode: "0600" }

- name: ldap-passwd-webui | Copy nginx server configs.
  copy:
    src: ldap-passwd-webui/nginx/conf.d/ldap-passwd-webui.conf
    dest: /h/toolset/nginx/conf.d/
    owner: toolset
    group: toolset
    mode: 0644
  notify: reload nginx
