---
- name: Create a default network.
  docker_network:
    name: default_network
  ignore_errors: "{{ ansible_check_mode }}"

- import_tasks: nginx.yml
  when: docker_rit_deploy_nginx == true

- import_tasks: portainer.yml
  when: docker_rit_deploy_portainer == true

- import_tasks: grafana.yml
  when: docker_rit_deploy_grafana == true
