---
- name: Create a directories for nginx it does not exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: toolset
    group: toolset
    mode: '0755'
  with_items:
    - /h/toolset/nginx
    - /h/toolset/nginx/log
    - /h/toolset/nginx/conf.d
    - /h/toolset/nginx/tls

- name: Copy nginx.conf.
  template:
    src: nginx/nginx.conf.j2
    dest: /h/toolset/nginx/nginx.conf
    owner: toolset
    group: toolset
    mode: 0644

- name: Create a nginx container.
  docker_container:
    name: nginx
    image: nginx:alpine
    networks:
      - name: "default_network"
    ports:
      - "80:80"
      - "443:443"
    restart_policy: unless-stopped
    volumes:
      - /h/toolset/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /h/toolset/nginx/log:/var/log/nginx
      - /h/toolset/nginx/conf.d:/etc/nginx/conf.d
      - /h/toolset/nginx/tls:/etc/nginx/tls
  ignore_errors: "{{ ansible_check_mode }}"
