---
# Setup/install tasks.
- import_tasks: os-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- import_tasks: os-debian.yml
  when: ansible_distribution == 'Debian'

- import_tasks: install.yml
  when: ansible_os_family == 'Debian'

# Package configuration.
- import_tasks: configs.yml
  when: ansible_os_family == 'Debian'
