---
- name: Install signing key.
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_package_install_version }}.asc
    state: present

- name: Add official mongodb repository.
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_package_install_version }} main
    filename: mongodb-{{ mongodb_package_install_version }}
