---
# Add repository
- import_tasks: repo.yml
  when: mysql_package_repo_enable

- name: Update apt cache.
  apt: update_cache=yes

- name: Ensure MySQL packages are installed latest version.
  apt: "name={{ mysql_packages }} state=latest"

- name: Ensure MySQL Python libraries are installed.
  apt: "name=python-mysqldb update_cache=yes state=present install_recommends=yes" # ?? add install_recommends=no for mysql 5.6
