---
- hosts: docker.rit
  vars:
    setting_environment: prod
    # standart-common
    install_updates: true
    install_utilites: true
    update_init: true
    change_local_hostname: false
    # proj-docker.rit
    docker_rit_deploy_nginx: true
    docker_rit_deploy_portainer: true #nginx required
    docker_rit_deploy_grafana: true #nginx required
    docker_rit_deploy_ldap_passwd_webui: true #nginx required
    docker_rit_deploy_bookstack: true #nginx required
  become: yes
  become_user: root
  roles:
     - { role: standart-common }
     - { role: tools-toolset }
     - { role: tools-docker }
     - { role: proj-docker }
     - { role: tools-zabbix-agent }
