---
- hosts: gateway
  vars:
    setting_environment: prod
    # standart-common
    install_updates: true
    upgrade_packages: true
    install_utilites: true
    update_init: true
    create_users: true
    user_list_deploy: "soikin"
    change_local_hostname: false
    firewall_allowed_ipv4_adresses:
      - "172.17.110.55"
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "443"
      - "3128"
      - "3129"
      - "1812"
      - "1813"
    firewall_ipv4_additional_rules:
      - "iptables -t nat -A POSTROUTING -o eth0 -s {{ squid_localnet }} -j MASQUERADE"
      - "iptables -t nat -A PREROUTING -s {{ squid_localnet }} -p tcp -m multiport --dports 80,8080 -j REDIRECT --to-ports 3128"
      - "iptables -t nat -A PREROUTING -s {{ squid_localnet }} -p tcp -m multiport --dports 443 -j REDIRECT --to-ports 3129"
    # standart-nginx
    nginx_repo_use: true
    nginx_default_conf_replace: true
    nginx_default_vhost_delete: true
    nginx_conf_enable_gzip: true
    nginx_static_enable_optimization: true
    nginx_default_http_port: 80
    nginx_default_https_port: 443
    # tools-toolset
    toolset_copy_certificates: true
    toolset_ip_listen_enable: true
    toolset_web_hostname: gateway.toolset.rit
    toolset_copy_nginx_config: true
    # standart-mysql
    mysql_delete_before_installation: true
    mysql_package_repo_enable: true
    mysql_package_repo_version: 5.7
    mysql_root_password: Ml4CuXAvoqI9EiFu
    mysql_create_databases: true
    mysql_create_users: true
    mysql_databases:
      - name: abills
        collation: utf8_general_ci
        encoding: utf8
    mysql_users:
      - name: abills
        host: localhost
        password: 34JoKbTNcnacbrvR
        priv: "abills.*:ALL"
    # standart-php
    php_default_version: 7.2
    php_default_conf_replace: true
    php_install_fpm_package: true
    php_install_project_packages: true
    php_list_project_packages:
      - php{{ php_default_version }}-mysql
    # tools-phpmyadmin
    phpmyadmin_nginx_phpfpm_config: true
    # standart-squid
    squid_conf_replace: true
    squid_localnet: 172.17.228.2/32
    squid_dns: 194.158.196.137
    squid_mitm: true
    # proj-billing
    billing_hostname: billing.rit
    billing_ssl: true
    billing_secret: ttR4b6xDvclhLbfY
  become: yes
  become_user: root
  roles:
     - { role: standart-common }
     - { role: standart-firewall }
     - { role: standart-nginx }
     - { role: tools-toolset }
     - { role: standart-mysql }
     - { role: standart-php }
     - { role: tools-phpmyadmin }
     - { role: standart-squid }
     - { role: proj-billing }
