---
- hosts: git.rit
  vars:
    setting_environment: prod
    # standart-common
    install_updates: true
    upgrade_packages: true
    install_utilites: true
    update_init: true
    change_local_hostname: false
    # standart-nginx
    nginx_repo_use: true
    nginx_default_conf_replace: true
    nginx_default_vhost_delete: true
    nginx_conf_enable_gzip: true
    nginx_static_enable_optimization: true
    nginx_default_http_port: 80
    nginx_default_https_port: 443
    # tools-web-proxy
    project_deploy_to_proxy_host: true
    project_web_proxy_sites_list:
    - name: "git.rit"
      proxy_ip: 127.0.0.1
      proxy_port: 3000
      tls: true
    # proj-git
    git_deploy: true
    git_backups: false
    git_version: 1.8.3
  become: yes
  become_user: root
  roles:
     - { role: standart-common }
     - { role: standart-nginx }
     - { role: tools-web-proxy }
     - { role: proj-git }
     - { role: tools-zabbix-agent }
