---
- hosts: all
  vars:
    setting_environment: prod
    # standart-common
    install_updates: true
    update_security: false
    install_utilites: true
    update_init: true
    change_local_hostname: false
  become: yes
  become_user: root
  roles:
     - { role: standart-common }
     - { role: tools-toolset }
     # - { role: tools-zabbix-agent }
