---
- name: fcgiwrap boot
  systemd:
    name: fcgiwrap
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
