---
- name: Ensures right permission for home directory.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /root
    - /root/.ssh

- name: Ensures ssh keys exists for project user.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "ssh/id_rsa", dest: "/root/.ssh/id_rsa", mode: "0600" }
    - { src: "ssh/id_rsa.pub", dest: "/root/.ssh/id_rsa.pub", mode: "0640" }

- name: Create a default network.
  docker_network:
    name: default_network
  ignore_errors: "{{ ansible_check_mode }}"
# ----------------------------------------------------------------------------
# Importing tasks:
- import_tasks: nginx.yml
  when: docker_rit_deploy_nginx == true

- import_tasks: portainer.yml
  when: docker_rit_deploy_portainer == true

- import_tasks: grafana.yml
  when: docker_rit_deploy_grafana == true

- import_tasks: ldap-passwd-webui.yml
  when: docker_rit_deploy_ldap_passwd_webui == true

- import_tasks: bookstack.yml
  when: docker_rit_deploy_bookstack == true
