---
- name: update ca certificates
  command: update-ca-certificates -v
  changed_when: false

- name: restart cron
  systemd: name=cron state=restarted

- name: restart ssh
  systemd: name=ssh state=restarted

- name: restart ntp
  systemd: name=ntp state=restarted
