---
- name: Enable IP forwarding.
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Stop squid service.
  systemd:
    name: squid
    state: stopped

- name: Remove old init.d script.
  file:
    state: absent
    path: /etc/init.d/squid

- name: Configure the squid systemctl service.
  template:
    src: squid.service.j2
    dest: "/etc/systemd/system/{{ squid_daemon }}.service"
  notify:
    - squid-boot
    - squid-start

- name: Create additional config directory.
  file:
    path: /etc/squid/ssl
    state: directory
    mode: 0755

- name: Creating certificates cache.
  command: "/usr/lib/squid/ssl_crtd -c -s /etc/squid/ssl/cert_cache"

- name: Setting correct attributes for cert_cache folder.
  file:
    path: /etc/squid/ssl/cert_cache
    owner: proxy
    group: proxy
    recurse: yes

- name: Copy additional config files..
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "squidCA.pem", dest: "/etc/squid/ssl/squidCA.pem", mode: "0600" }
    - { src: "forbidden-en.html", dest: "/usr/share/squid/errors/en/ERR_ACCESS_DENIED", mode: "0644" }
    - { src: "forbidden-ru.html", dest: "/usr/share/squid/errors/ru/ERR_ACCESS_DENIED", mode: "0644" }
  when: squid_mitm
  tags: squid-config

- name: Copy block-list for mitm configuration.
  copy:
    src: blocked_regexp.txt
    dest: /etc/squid/blocked.txt
  when: squid_mitm
  tags: squid-config

- name: Copy block-list for transparent configuration.
  copy:
    src: blocked.txt
    dest: /etc/squid/blocked.txt
  when: not squid_mitm
  tags: squid-config

- name: Copy squid configuration in place.
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
  when: squid_conf_replace
  notify:
    - squid-reconfigure
  tags: squid-config

- name: Copy logrotate configuration in place.
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/squid
