---
- name: Install utilites.
  apt:
    pkg: ['fakeroot', 'build-essential', 'devscripts', 'libecap3', 'libecap3-dev', 'libssl1.0-dev', 'libgnutls28-dev']
    update_cache: yes
    cache_valid_time: 86400
    state: present

- name: Install dependencies for squid packages.
  apt:
    pkg: ['apache2', 'apache2-bin', 'apache2-data', 'apache2-utils', 'libapr1', 'libaprutil1', 'libaprutil1-dbd-sqlite3', 'libaprutil1-ldap', 'libdbi-perl', 'liblua5.2-0', 'squid-langpack', 'ssl-cert']
    update_cache: yes
    cache_valid_time: 86400
    state: present
  notify:
    - apache2-stop
    - apache2-disable

- name: Ensures the squid3 build dependencies are installed.
  apt:
    name: squid3
    state: build-dep

- name: Copy deb packages to /tmp.
  copy:
    src: "squid-3.5.28/{{ item }}.deb"
    dest: "/tmp/{{ item }}.deb"
  with_items:
    - squid-common_3.5.28-1_all
    - squid_3.5.28-1_amd64
    - squid-cgi_3.5.28-1_amd64
    - squid-dbg_3.5.28-1_amd64
    - squid-purge_3.5.28-1_amd64
    - squid3_3.5.28-1_all
    - squidclient_3.5.28-1_amd64


- name: Install squid deb packages.
  apt:
    deb: "/tmp/{{ item }}.deb"
    state: present
    force: yes
  with_items:
    - squid-common_3.5.28-1_all
    - squid_3.5.28-1_amd64
    - squid-cgi_3.5.28-1_amd64
    - squid-dbg_3.5.28-1_amd64
    - squid-purge_3.5.28-1_amd64
    - squid3_3.5.28-1_all
    - squidclient_3.5.28-1_amd64
  ignore_errors: "{{ ansible_check_mode }}"
