---
- name: Copy nginx project web-proxy configs.
  template: src=nginx-proxy.conf.j2 dest=/etc/nginx/sites-available/1-{{ item.name }}.conf
  with_items: "{{ project_web_proxy_sites_list }}"
  notify: reload nginx

- name: Enable nginx project web-proxy configs.
  file: src=/etc/nginx/sites-available/1-{{ item.name }}.conf dest=/etc/nginx/sites-enabled/1-{{ item.name }}.conf state=link
  ignore_errors: "{{ ansible_check_mode }}"
  with_items: "{{ project_web_proxy_sites_list }}"
  notify: restart nginx

- name: Copy nginx proxy_pass config.
  template: src=nginx-web-proxy.conf.j2 dest=/etc/nginx/nginx-web-proxy.conf
  notify: reload nginx
