---
- name: domain | Install packages.
  package:
    name: [realmd, sssd, oddjob, oddjob-mkhomedir, adcli, samba-common, samba-common-tools, python-pip]
    state: present

- name: domain | Install pexpect using pip
  pip:
    name: pexpect
  ignore_errors: "{{ ansible_check_mode }}"

- name: domain | Join system to AD and put the computer object in the Linux OU
  expect:
    command: /bin/bash -c "/usr/sbin/realm join --user=Administrator@rit.va rit.va"
    responses:
      Password for *: "{{ init_domin_admin_password }}"

- name: domain | Configure sssd.
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    dest: /etc/sssd/sssd.conf
  with_items:
    - {regexp: "^use_fully_qualified_names = ", line: "use_fully_qualified_names = False"}
    - {regexp: "^fallback_homedir = ", line: "fallback_homedir = /home/%u"}

- name: domain | Allow domain users to create home directories.
  command: /usr/sbin/authconfig --enablemkhomedir --enablesssdauth --updateall

- name: domain | Start sssd
  systemd:
    name: sssd
    state: restarted
    enabled: yes

- name: domain | Make userrit folder readable to other users.
  file:
    path: /home/userrit
    state: directory
    mode: '0755'

- name: domain | Disable login to userrit.
  lineinfile:
    regexp: '^userrit:x:1000:1000'
    line: "userrit:x:1000:1000:userrit:/home/userrit:/bin/false"
    dest: /etc/passwd
