---
- name: usbguard | install usbguard
  package:
    name: usbguard
    state: present

- name: usbguard | Create white list.
  script: usb-policy.sh

- name: usbguard | Start usbguard
  systemd:
    name: usbguard
    state: started
    enabled: yes

- name: usbguard | Create a usb-ipc directory if it does not exist
  file:
    path: /root/usb-ipc
    state: directory
    mode: '0755'

- name: usbguard | Copy usb-ipc-manager.sh script.
  copy:
    src: usb-ipc-manager.sh
    dest: /root/usb-ipc/usb-ipc-manager.sh
    mode: 755
