---
# Please override this setting in role playbook
mysql_root_username: root
mysql_root_password: mysqlvarb
# Set this to `yes` to forcibly update the root password.
mysql_root_password_update: no

mysql_enabled_on_startup: yes
mysql_secure_installation: true
mysql_delete_before_installation: false
mysql_upgrade_packages: false
mysql_create_databases: false
mysql_create_users: false
mysql_default_conf_replace: false
mysql_package_repo_enable: false
mysql_package_repo_version: "" # 5.6 or 5.7 or 8.0

mysql_datadir: /var/lib/mysql
mysql_user_home: /root
mysql_daemon: mysql
mysql_packages:
  - mysql-server

# Databases.
mysql_databases: []
#   - name: example
#     collation: utf8mb4_general_ci
#     encoding: utf8mb4
#     replicate: 1

# Users.
mysql_users: []
#   - name: example
#     host: 127.0.0.1
#     password: secret
#     priv: *.*:USAGE
