---
- name: Check security settings in sshd config.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?{{ item.regex }}"
    line: "{{ item.line }}"
    validate: '/usr/sbin/sshd -T -f %s'
  with_items:
   - {regex: "PermitRootLogin", line: "PermitRootLogin without-password"}
   - {regex: "PermitEmptyPasswords", line: "PermitEmptyPasswords no"}
   - {regex: "PubkeyAuthentication", line: "PubkeyAuthentication yes"}
  notify: restart ssh
  when: ansible_distribution == 'Debian'

- name: Make sure a rpcbind.service is stopped.
  systemd: name=rpcbind state=stopped enabled=no
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'
