---
- name: Install standart utilites
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - aptitude
    - bash-completion
    - curl
    - dnsutils
    - git
    - htop
    - iftop
    - iotop
    - iptraf
    - mc
    - nano
    - ntp
    - ncdu
    - nmap
    - nmon
    - psmisc
    - rsync
    - screen
    - sysstat
    - unzip
    - vim
    - sudo
    - net-tools
    - openssl
  tags: utilites

- name: Install extra utilites
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - "{{ install_extra_utilites }}"
  when: install_extra_utilites is defined
  tags: utilites

- name: Ensure the system can use the HTTPS transport for APT
  stat: path=/usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt: pkg=apt-transport-https state=present
  when: not apt_https_transport.stat.exists
