---
# Nginx configuration.
- name: Copy nginx configuration in place
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
