---
# Setup/install tasks.
- import_tasks: mainline.yml
  when: ansible_os_family == 'Debian'

- import_tasks: os-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- import_tasks: os-debian.yml
  when: ansible_distribution == 'Debian'

- import_tasks: install.yml
  when: ansible_os_family == 'Debian'

# Nginx configuration.
- import_tasks: configs.yml
  when: nginx_default_conf_replace

# Vhost configuration.
- import_tasks: vhosts.yml
  when: nginx_default_vhost_delete

# Nginx start at boot
- name: Ensure nginx is enabled to start at boot.
  service: name=nginx enabled=yes
  notify: restart nginx
  ignore_errors: "{{ ansible_check_mode }}"
