---
- name: Remove default vhost enabled symlink.
  file:
    dest=/etc/nginx/sites-enabled/default
    state=absent
  notify: restart nginx

- name: Remove default vhost.
  file:
    dest=/etc/nginx/sites-available/default
    state=absent

- name: Remove default configs (new version).
  file:
    dest=/etc/nginx/conf.d/default.conf
    state=absent
